#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(NICTA_GPL)
#

apps-$(CONFIG_APP_TIMER_TK1)    += timer_tk1

timer_tk1: common libsel4 libmuslc libsel4vka libsel4muslcsys \
libsel4utils libutils libsel4camkes libsel4sync libsel4debug libsel4muslccamkes libplatsupport 

